---
title: "distritos_info"
author: "Eva Cantín"
date: "8/4/2022"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
valencia = read.csv("venta_pisos.csv", sep=';', row.names = 1, as.is = FALSE)

valencia = valencia[!is.na(valencia$ad_characteristics_constructedArea),]

valencia = valencia[valencia$planta < 35,]
plantadata = valencia[!is.na(valencia$planta),]

valencia$ad_characteristics_hasParking[is.na(valencia$ad_characteristics_hasParking)] = 0

valencia$ad_characteristics_hasLift[is.na(valencia$ad_characteristics_hasLift)] = 0

valencia$ad_characteristics_hasSwimmingPool[is.na(valencia$ad_characteristics_hasSwimmingPool)] = 0

valencia$ad_characteristics_hasTerrace[is.na(valencia$ad_characteristics_hasTerrace)] = 0

valencia$ad_characteristics_hasGarden[is.na(valencia$ad_characteristics_hasGarden)] = 0


#CREAMOS LAS FILAS PARA DISTRITO:
auxi = valencia %>% group_by(distrito)  %>%
                    summarise(media_m2 = mean(ad_characteristics_constructedArea), 
                              num_pisos=n(), media_hab = mean(ad_characteristics_roomNumber), 
                              porc_reformar= sum(ad_condition_isNeedsRenovating==1)/n()*100,                               porc_inmobiliaria=sum(ad_owner_type==2)/num_pisos*100,
                              porc_parking=sum(ad_characteristics_hasParking==1)/n()*100,
                              porc_ascensor=sum(ad_characteristics_hasLift==1)/n()*100,
                              porc_piscina=sum(ad_characteristics_hasSwimmingPool==1)/n()*100,
                              porc_terraza=sum(ad_characteristics_hasTerrace)/n()*100,
                              porc_jardin=sum(ad_characteristics_hasGarden)/n()*100)

auxi = auxi[1:19,]
auxi2 = plantadata %>% group_by(distrito) %>% summarise(media_planta = mean(planta))
df_final = cbind(auxi, auxi2[,2])
```

```{r juntamos}
library("readxl")
df = read.csv("distritos_info.csv", sep=";")

df<- df[order(df$distrito), ]
df_final_concat = df_final[, 2:12]

df1 = cbind(df, df_final_concat)
df2 = df1 %>% group_by(distrito) %>% summarise(porc_vendidos = sum(`pisos vendidos`/num_pisos*100))

distrito_info = cbind(df1, df2[,2])
#write.csv2(distrito_info, "distrito_info1.csv")
```

```{r excel adri}
df3 = read.csv2("distrito_info1.csv")
df3[,31:36] = apply(df3[ , 31:36], 2, function(x) x*100)
#write.csv2(df3, "distritos_info.csv")
```


df4 = read.csv2("distritos_info.csv")
class(df4$densidad)

